-- vim.g.tmux_navigator_no_mappings = 1
--
-- vim.cmd[[nnoremap <silent> <M-h> :TmuxNavigateLeft<cr>]]
-- vim.cmd[[nnoremap <silent> <M-j> :TmuxNavigateDown<cr>]]
-- vim.cmd[[nnoremap <silent> <M-k> :TmuxNavigateUp<cr>]]
-- vim.cmd[[nnoremap <silent> <M-l> :TmuxNavigateRight<cr>]]
